title: Nerdfury
header-img: img/home-bg.jpg
email: nerdfury@fivedegrees.co.uk
copyright_name: nerdfury
description: "Random ramblings of an idiot"
url: "http://nerdfury.me"
twitter_username: iamnerdfury
github_username: nerdfury
email_username: nerdfury@fivedegrees.co.uk

google_tracking_id: "UA-39636175-2"

markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less"]
